// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRcDSIWstOA0uGS5UnAyNxTDyRdNDfFvU',
    appId: '1:112179950806:web:be748d013d0b6f960e8577',
    messagingSenderId: '112179950806',
    projectId: 'chature-ab54e',
    authDomain: 'chature-ab54e.firebaseapp.com',
    storageBucket: 'chature-ab54e.appspot.com',
    measurementId: 'G-VN5S4FF2YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrL8YK9w9NgOsTnCHx58B_5oY_BRgFCwY',
    appId: '1:112179950806:android:a617e7572a34ff670e8577',
    messagingSenderId: '112179950806',
    projectId: 'chature-ab54e',
    storageBucket: 'chature-ab54e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDZCHQUF1V3c4cnJRmrd3jNO6FlH4kPM8',
    appId: '1:112179950806:ios:190a87d66f1effa90e8577',
    messagingSenderId: '112179950806',
    projectId: 'chature-ab54e',
    storageBucket: 'chature-ab54e.appspot.com',
    iosBundleId: 'com.example.chature1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDZCHQUF1V3c4cnJRmrd3jNO6FlH4kPM8',
    appId: '1:112179950806:ios:190a87d66f1effa90e8577',
    messagingSenderId: '112179950806',
    projectId: 'chature-ab54e',
    storageBucket: 'chature-ab54e.appspot.com',
    iosBundleId: 'com.example.chature1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRcDSIWstOA0uGS5UnAyNxTDyRdNDfFvU',
    appId: '1:112179950806:web:d1421cf377446e660e8577',
    messagingSenderId: '112179950806',
    projectId: 'chature-ab54e',
    authDomain: 'chature-ab54e.firebaseapp.com',
    storageBucket: 'chature-ab54e.appspot.com',
    measurementId: 'G-N8MZMFRZ40',
  );

}